language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3

before_script:
  - travis_retry composer self-update
  - alias composer="php -d zend.enable_gc=0 /usr/bin/composer"
  - travis_retry composer install --no-interaction --prefer-source

script: 
  - bin/phpunit --coverage-text
